config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  # get 'review/new'
  # get 'attendance/show'
  # get 'attendance/index'
  # get 'venue/show'
  # get 'venue/index'
  # get 'events/new'
  # get 'events/update'
  # get 'events/index'
  # get 'events/show'
  resources :venues do
    resources :bookings, only: [:create, :new, :show, :edit, :destroy] do
      resources :events, only: [:create, :new, :show, :edit, :destroy, :update] do
        resources :attendances, only: [:create, :new]
      end
    end
  end

  resources :attendances, only: [:update, :show, :index]

  resources :friend_requests


  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root to: "pages#home"
  get 'events/index', to: 'events#index', as:'myevent_list'
  get 'pages/show', to: 'pages#show', as:'front_page'
  get 'booking/index', to: 'bookings#index', as: 'booking_listing_path'

  # patch 'attendances/update', to: 'attendances#update', as: 'update_page'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    @user = policy_scope(User)
    @user = current_user
    

    # @booking_id = @booking.map{ |event| event.venue_id}

    # add if no event raise currently no event

  end
  def show
    @user = User.find(params[:id])
    authorize @user
  end

end

app/views/profiles/index.html.erb
<div class="container">
  <div class="row" id="profileall">
    <div class="profile-header d-flex mt-3">
      <%= link_to front_page_path do %>
        <i class="fa-solid fa-arrow-left" id="arrow_left"></i>
      <% end %>
      <h3>Profile</h3>
      <div class="col-md-3" id="logout">
        <%= link_to "Log out", destroy_user_session_path,  data: {turbo_method: :delete}, class: "dropdown-item" %>
      </div>
    </div>

    <div class="col-md-12" id="profile">
      <div class="profile-photo">
        <%= image_tag @user.image_url %>
      </div>
      <div class="profile-info">
        <h3><%= @user.first_name %> <%= @user.last_name %></h4>
        <h4><%= @user.email %></p>
        <p><%= @user.phone_number %></p>
        <p><%= @user.dietary %></p>
      </div>
    </div>
  </div>
    <div class="col-md-12 d-flex mt-3" id="profilebox" style="justify-content:space-around;">
      <p class="venue"><%= link_to "My Venues", venues_path%><i class="fa-solid fa-arrow-right" id="arrow_right"></i></p>
      <p class="event"><%= link_to "Events", myevent_list_path %><i class="fa-solid fa-arrow-right" id="arrow_right"></i></p>
    </div>
    <div class="col-12" id="listoffriend">
      <h3>Friend Listing</h3>
      <% @friendlist = current_user.friends %>
      <div class="list" >
        <% @friendlist.each do|f| %>
          <%= link_to profile_path(f.id) do%>
            <div class="d-flex align-items-center" style="margin-bottom: 20px; margin-left:60px;">
              <!-- User Image with Margin -->
              <div class="user-image-container">
                <%= image_tag f.image_url, alt: "User Image", class: "img-fluid rounded-circle mr-3", style: "width: 50px; height: 50px;" %>
              </div>
              <!-- User Name -->
              <span id="friend_list_profile"><%= f.first_name + ' ' + f.last_name %></span>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>


  <div class="row">
    <%= render 'shared/footer' %>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="container">
  <div class="row" id="profileall">
    <div class="profile-header d-flex mt-3">
      <%= link_to profiles_path do %>
        <i class="fa-solid fa-arrow-left" id="arrow_left"></i>
      <% end %>
      <h3>Profile</h3>
      <div class="col-md-3" id="logout">
        <%= link_to "Log out", destroy_user_session_path,  data: {turbo_method: :delete}, class: "dropdown-item" %>
      </div>
    </div>

    <div class="col-md-12" id="profile">
      <div class="profile-photo">
        <%= image_tag @user.image_url %>
      </div>
      <div class="profile-info">
        <h3><%= @user.first_name %> <%= @user.last_name %></h4>
        <h4><%= @user.email %></p>
        <p><%= @user.phone_number %></p>
        <p><%= @user.dietary %></p>
      </div>
    </div>
  </div>
</div>