config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  # get 'review/new'
  # get 'attendance/show'
  # get 'attendance/index'
  # get 'venue/show'
  # get 'venue/index'
  # get 'events/new'
  # get 'events/update'
  # get 'events/index'
  # get 'events/show'
  resources :venues do
    resources :bookings, only: [:create, :new, :show, :edit, :destroy] do
      resources :events, only: [:create, :new, :show, :edit, :destroy, :update] do
        resources :attendances, only: [:create, :new]
      end
    end
  end

  resources :attendances, only: [:update, :show, :index]

  resources :friend_requests


  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root to: "pages#home"
  get 'events/index', to: 'events#index', as:'myevent_list'
  get 'pages/show', to: 'pages#show', as:'front_page'
  get 'booking/index', to: 'bookings#index', as: 'booking_listing_path'

  # patch 'attendances/update', to: 'attendances#update', as: 'update_page'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_flashes.html.erb
<%# use this if we wantan alert. maybe not required for mobile version %>

<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footernav">
  <div class="col-12" id="footer">
    <%= link_to root_path do %>
      <i class="fa-solid fa-home" style="color: #b96cd5;"></i>
    <% end %>

    <%= link_to  front_page_path do %>
      <i class="fa-solid fa-magnifying-glass" style="color: #b96cd5;"></i>
    <% end %>

    <%= link_to attendances_path do %>
      <i class="fa-solid fa-bell" style="color: #b96cd5;"></i>
    <% end %>

    <%= link_to myevent_list_path do %>
      <i class="fa-regular fa-calendar" style="color: #b96cd5;"></i>
    <% end %>

    <% if user_signed_in? %>
      <%= link_to profiles_path do %>
        <i class="fa-regular fa-user" style="color: #b96cd5;"></i>
      <% end %>
    <% else %>
      <div class="nav-item">
        <%= link_to new_user_session_path do %>
          <i class="fa-solid fa-user-lock" style="color: #b96cd5;"></i>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path '/app/assets/images/icons' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path '/app/assets/images/icons' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path '/app/assets/images/icons' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path '/app/assets/images/icons' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path '/app/assets/images/icons' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path '/app/assets/images/icons' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path '/app/assets/images/icons' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path '/app/assets/images/icons' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path '/app/assets/images/icons' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path '/app/assets/images/icons' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path '/app/assets/images/icons' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path '/app/assets/images/icons' %>">

app/views/shared/_navbar.html.erb
<div class="phonenavbar">
  <div class="row">
    <div class="col-md-10" id="navbar_search" style="justify-content:center;">
      <%= form_with url: front_page_path, method: :get, class: "tool-form d-flex" do %>
        <i class="fa-solid fa-location-dot" id="location-nav"></i>
        <%= text_field_tag :location, params[:location], class: "form-control", placeholder: "Search.." %>
        <%= submit_tag "", name: "", class: "btn search-btn" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_searchform.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <%= simple_form_for @venue do |f| %>
        <%= f.input :number_of_people %>
        <%= f.input :start_date %>
        <%= f.submit class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>