config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  # get 'review/new'
  # get 'attendance/show'
  # get 'attendance/index'
  # get 'venue/show'
  # get 'venue/index'
  # get 'events/new'
  # get 'events/update'
  # get 'events/index'
  # get 'events/show'
  resources :venues do
    resources :bookings, only: [:create, :new, :show, :edit, :destroy] do
      resources :events, only: [:create, :new, :show, :edit, :destroy, :update] do
        resources :attendances, only: [:create, :new]
      end
    end
  end

  resources :attendances, only: [:update, :show, :index]

  resources :friend_requests


  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root to: "pages#home"
  get 'events/index', to: 'events#index', as:'myevent_list'
  get 'pages/show', to: 'pages#show', as:'front_page'
  get 'booking/index', to: 'bookings#index', as: 'booking_listing_path'

  # patch 'attendances/update', to: 'attendances#update', as: 'update_page'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  belongs_to :booking
  has_many :attendances, dependent: :destroy
  has_one_attached :photo, dependent: :destroy
  validates :event_name, :photo, :meal_dietary, :additional, presence:true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
before_action:set_event, only:[:edit, :show, :destroy, :update]

  def new
    @event = Event.new
    @booking= Booking.find(params[:booking_id])
    @venue = Venue.find(@booking.venue_id)
    authorize @event # Add this line
  end

  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    @event.booking_id = params[:booking_id]
    authorize @event
    if @event.save!

      redirect_to venue_booking_event_path(params[:venue_id], @event.booking_id, @event.id)

    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @event
  end

  def update
    authorize @event
  end

  def index
    @user = current_user
    @event = policy_scope(Event)
    @event = Event.where(user_id: @user.id )
    @attendances = Attendance.where(user_id: @user.id, status: "true")
    @attendances = @attendances.map do |attendance|
      attendance.event_id
    end
    @events_going_for = Event.where(id: @attendances)
    @event = Event.where(user_id: @user.id ) + @events_going_for
  end

  def show
    authorize @event
    @booking = Booking.find(params[:booking_id])
    @venue = Venue.find(Booking.find(params[:booking_id]).venue_id)
    @users = User.where.not(id: current_user.id)
    @booking = Booking.find(@event.booking_id)
    @attendance = Attendance.where(event_id: @event.id)

    if params[:user].present?
      sql_subquery = "first_name ILIKE :user OR last_name ILIKE :user"
      @users = @users.where(sql_subquery, user: "%#{params[:user]}%")
    end
  end

  def destroy
    @event.booking_id = params[:booking_id]
    @event.destroy
    redirect_to myevent_list_path
    authorize @event
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:event_name, :event_detail, :dress_code, :number_of_people, :time, :start_date, :end_date, :photo, :accomodation, :additional => [], :meal_dietary => [] )
  end
end

app/views/events/_form.html.erb
<%= simple_form_for([@venue, @booking, @event]) do |f| %>
  <p><%= f.input :event_name, placeholder:"what are you planning?" %></p>
  <p><%= f.input :photo, as: :file %></p>
  <p><strong>Address:</strong> <%= @venue.name %>,  <%= @venue.address %> </p>
  <%# useflatpicker %>

  <% if !(@booking.date == nil) %>
    <p><strong>Date:</strong> <%= @booking.date.strftime("%A, %e %B %Y") %></p>
    <p><strong>Time:</strong> <%= @booking.time.strftime("%l %P") %></p>
    <p><strong>People:</strong> <%= @booking.people %></p>

  <% else %>
    <%= f.input :start_date , as: :string, input_html: { data: { controller: "datepicker" } } %>
    <%= f.input :time %>
    <%= f.input :number_of_people, collection: 1..300  %>
  <% end %>
  <%= f.input :event_detail, as: :text, placeholder:"what is the plan?"%>


  <%= f.input :meal_dietary, collection:[
  "Vegetarian",
  "Vegan",
  "Gluten-Free",
  "Dairy-Free",
  "Low-Carb/Keto",
  "Allergen-Free"], as: :check_boxes , placeholder:"Meal options" %>

  <%= f.input :additional, collection:['Dog-Friendly', 'Kid-friendly', 'BYO', 'Cash Required'], as: :check_boxes %>

  <%= f.input :dress_code, collection:
  ["Smart", "Casual", "Colour Theme", "Haloween",
  "Formal",
  "Business Formal",
  "Business Casual",
  "Smart Casual",
  "Black Tie",
  "White Tie",
  "Cocktail Attire",
  "Festive Attire",
  "Semi-Formal"] %>


  <%= f.submit class: "btn btn-primary", id:"event-btn" %>
<% end %>

app/views/events/_new_release.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">x</button>
  <h4 class="modal-title" id="myModalLabel">Modal title</h4>
</div>
<div class="modal-body">
  <%= render 'attendances/form' %>
</div>
<div class="modal-footer">
  <button class="btn btn-primary">Save</button>
</div>

app/views/events/edit.html.erb
<%= simple_form_for([@venue, @booking, @event]) do |f| %>
  <p><%= f.input :event_name, placeholder:"what are you planning?" %></p>
  <p><%= f.input :photo, as: :file %></p>
  <p><strong>Address:</strong> <%= @venue.name %>,  <%= @venue.address %> </p>
  <%# useflatpicker %>
  <% if @booking.present? %>
    <p><strong>Date:</strong> <%= @booking.date %></p>
    <p><strong>Time:</strong> <%= @booking.time %></p>
  <% else %>
    <%= f.input :start_date , as: :string, input_html: { data: { controller: "datepicker" } } %>
    <%= f.input :time %>
  <% end %>

  <%= f.input :event_detail, as: :text, placeholder:"what is the plan?"%>
  <%= f.input :meal_dietary, collection:[
  "Vegetarian",
  "Vegan",
  "Gluten-Free",
  "Dairy-Free",
  "Low-Carb/Keto",
  "Allergen-Free"], as: :check_boxes , placeholder:"Meal options" %>

  <%= f.input :additional, collection:['Dog-Friendly', 'Kid-friendly', 'BYO', 'Cash Required'], as: :check_boxes %>
  <%= f.input :number_of_people, collection: 1..300  %>
  <%= f.input :dress_code, collection:
  ["Smart", "Casual", "Colour Theme", "Haloween",
  "Formal",
  "Business Formal",
  "Business Casual",
  "Smart Casual",
  "Casual",
  "Black Tie",
  "White Tie",
  "Cocktail Attire",
  "Festive Attire",
  "Semi-Formal"] %>

  <%= f.submit class: "btn btn-primary", id:"event-btn" %>
<% end %>

app/views/events/index.html.erb
<div class="container">
  <div class="row" id="eventlistrow">
    <div class="col-md-12 d-flex" id="eventlist">
      <%= link_to root_path do %>
          <i class="fa-solid fa-arrow-left" id="arrow_left"></i>
        <% end %>
      <h3>Events</h3>
    </div>

    <% if @event.length > 0 %>
      <div class="col-md-12" id="eventlistdetail">
        <% @event.each do |e| %>
        <div class="eventlistcard d-flex mt-3" style="justify-content: space-between;">
          <div class="col-md-3" id="eventlistphoto" style="align-self: center;">
            <% if e.photo.key  %>
              <%= cl_image_tag e.photo.key, height: 100, width: 100, crop: :fill %>
            <% else %>
              <%= image_tag "https://placehold.co/100x100/png" %>
            <% end %>
          </div>
          <div class="col-md-9" id="eventdetail">
            <h3><%= e.event_name %></h3>
            <p><%= e.start_date %></p>
            <% @booking = Booking.find(e.booking_id) %>
            <% @venue = Venue.find(@booking.venue_id) %>
            <p><%= @venue.address %></p>
            <p><%= @venue.name %></p>
            <%= link_to "View Detail", venue_booking_event_path(@venue.id, @booking.id, e.id) %>
          </div>
        </div>
        <% end %>
      </div>
    <% else %>
  </div>
      <div class="row" id="noevent">
        <h3>No events. <%= link_to "Start planning.", front_page_path %></h3>
        <%= image_tag asset_path('nothing-here.png') %>
      </div>
    <% end %>

  <div class ="row"><%= render 'shared/footer'%>
  </div>
</div>

app/views/events/new.html.erb
<div class="container">
  <div class="row" style="background-color:#9395D3;">
    <div class="col-sm-12" id="eventform">
      <h3>Let's get planning!</h3>
    </div>
    <div class="col-sm-12" id="innereventform">
      <%= render "form"%>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12" id="imgshow" style="background-image: linear-gradient(rgb(77 15 15 / 45%), rgb(247 247 247 / 30%)), url('<%= cl_image_path @event.photo.key, height:200, width:400, crop: :fit%>')" >
      <div class="col-md-12 d-flex" id="eventshowpage">
        <%= link_to profiles_path do %>
          <i class="fa-solid fa-arrow-left" id="arrow_left"></i>
        <% end %>
        <h3>Event Details </h3>
          <%= link_to venue_booking_event_path(@venue.id, @event.booking_id, @event.id, ), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this event?" } do %>
            <i class="fa-regular fa-trash-can"></i>
          <% end %>
      </div>
    </div>

    <div class="col-sm-12 col-md-6" id="eventshowpage-detail">
      <h3><%= @event.event_name %></h3>
      <p>Hosted by</p>
      <div class="d-flex align-items-center" style="margin-bottom: 20px;">
        <!-- User Image with Margin -->
        <div class="user-image-container">
          <%= image_tag User.find(@event.user_id).image_url, alt: "User Image", class: "img-fluid rounded-circle mr-3", style: "width: 50px; height: 50px;" %>
        </div>
        <!-- User Name -->
        <span id="request_name"><%= User.find(@event.user_id).first_name + ' ' + User.find(@event.user_id).last_name %></span>
      </div>

      <div class="venuesecondetails d-flex">
        <i class="fa-regular fa-calendar"></i>
        <div class="venuesecondetail">
          <% if @event.start_date %>
            <p><strong><%= @event.start_date.strftime("%A, %e %B %Y") %></strong></p>
          <% else %>
            <p><strong><%= @booking.date.strftime("%A, %e %B %Y") %></strong></p>
          <% end %>
          <% if @event.time %>
            <p><%= @event.time.strftime("at %l %P") %></p>
          <% else %>
            <p><%= @booking.time.strftime("at %l %P") %></p>
          <% end %>
        </div>

      </div>

      <div class="venueaddresss d-flex">
        <i class="fa-solid fa-location-dot"></i>
        <div class="venueaddress">
          <p><strong><%= @venue.name %></strong></p>
          <p><%= @venue.address %></p>
        </div>
      </div>
    </div>

    <div class="col-sm-12" id="attendances">
      <% @number = 0 %>
      <% @attendance.each do |e| %>
        <% if e.status == "true" %>
          <% @number += 1 %>
        <% end %>
      <% end %>

      <h3 style="margin-bottom: 20px;">Who's going?</h3>
      <% if @number == 1%>
        <div class="attstatus d-flex">
          <%= link_to attendance_path do %>
            <i class="fa-solid fa-users"></i>
          <% end %>
          <p><%= @number %> person is going </p>
        </div>
      <% elsif @number < 1 || @number > 1 %>
        <div class="attstatus d-flex">
          <%= link_to attendance_path do %>
            <i class="fa-solid fa-users"></i>
          <% end %>
          <p><%= @number %> people are going </p>
        </div>
      <% else %>
        <div class="attempty d-flex">
          <i class="fa-solid fa-users"></i>
          <p>Invite Guests</p>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12" id="eventshowpage-description">
      <h3>Event Details</h3>
      <p><%= @event.event_detail %></p>
      <p><strong>Additional Information:</strong> </p>
      <p><%= @event.additional.reject(&:empty?).join(' - ') %></p>
      <p><strong>Catering Information:</strong>  </p>
        <p><%= @event.meal_dietary.reject(&:empty?).join(' - ') %></p>
      <p><strong>Dress Code:</strong> <%= @event.dress_code%></p>
    </div>
  </div>
  <div class="row">
    <div class="floatbutton">
      <%= link_to 'Invite Guests',  new_venue_booking_event_attendance_path(@venue.id, @event.booking_id, @event.id, ),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-primary btn-lg'}  %>
    </div>
  </div>

</div>