config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  # get 'review/new'
  # get 'attendance/show'
  # get 'attendance/index'
  # get 'venue/show'
  # get 'venue/index'
  # get 'events/new'
  # get 'events/update'
  # get 'events/index'
  # get 'events/show'
  resources :venues do
    resources :bookings, only: [:create, :new, :show, :edit, :destroy] do
      resources :events, only: [:create, :new, :show, :edit, :destroy, :update] do
        resources :attendances, only: [:create, :new]
      end
    end
  end

  resources :attendances, only: [:update, :show, :index]

  resources :friend_requests


  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root to: "pages#home"
  get 'events/index', to: 'events#index', as:'myevent_list'
  get 'pages/show', to: 'pages#show', as:'front_page'
  get 'booking/index', to: 'bookings#index', as: 'booking_listing_path'

  # patch 'attendances/update', to: 'attendances#update', as: 'update_page'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/venue.rb
class Venue < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :bookings, dependent: :destroy
  validates :name, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action:set_venue, only: [:show, :edit, :update]
  skip_before_action :authenticate_user!, only: :show

  def new
    @venue = Venue.new
    @booking = Booking.new
    authorize @venue
    if user_signed_in?
      if Attendance.exists?(user_id: current_user.id)
        @attendance = Attendance.where(user_id: current_user.id)
      end
    end
  end

  def create
    @venue = Venue.new(venue_params)
    @user = current_user
    @venue.user_id = @user.id
    authorize @venue
    if @venue.save!
      @booking = Booking.create(venue_id: @venue.id)
      redirect_to venue_booking_path(@venue.id, @booking.id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    authorize @venue
    @venue = Venue.find(params[:id])
    @booking = Booking.where(venue_id: @venue)
  end

  def edit
    authorize @venue
  end

  def update
    authorize @venue
  end

  def index
    @user_id = current_user.id
    @venue = policy_scope(Venue)
    @venue = Venue.where(user_id:@user_id)
  end

  private
  def booking_params
    params.require(:booking).permit(:date, :time, :people)
  end

  def venue_params
    params.require(:venue).permit(:name, :description, :address)
  end

  def set_venue
    @venue = Venue.find(params[:id])
  end

end

app/views/venues/_bookingform.html.erb
<div class="row">
  <div class="col-md-12" id="floatbook">
    <%= link_to "Book Venue", new_venue_booking_path(@venue.id) %>
  </div>
</div>

app/views/venues/_form.html.erb
<%= simple_form_for @venue do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :address, input_html: {data: {address_autocomplete_target: "address"}},
  wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}} %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/venues/edit.html.erb
<%= render 'form' %>

app/views/venues/index.html.erb
<div class="container">
  <div class="row" id="venuerow">
    <div class="col-md-12 d-flex" id="venuelistingtitle">
      <%= link_to profiles_path do %>
        <i class="fa-solid fa-arrow-left" id="arrow_left"></i>
      <% end %>
      <h3>My Venues</h3>
    </div>
    <% if @venue.length > 0  %>
      <div class="col-md-12" id="listing-card">
        <% @venue.each do |v|%>
          <div class="listinginner d-flex" style="justify-content: space-between;">
            <div class="col-md-12" id="inner_listing">
              <h3><%= v.name %></h3>
              <p><%= v.address %></p>
            </div>
            <div class="col-md-3" id="edit_button">
              <%= link_to edit_venue_path(v.id) do %>
                <i class="fa-solid fa-ellipsis-vertical"></i>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
      <% else %>
  </div>
        <div class="row" id="novenue">
          <h3>No venues. <%= link_to "Start creating.", new_venue_path %></h3>
          <%= image_tag asset_path('nothing-here.png') %>
        </div>
      <% end %>
</div>

app/views/venues/new.html.erb
<div class="container">
  <div class="row" id="myvenue">
    <div class="col-md-12 d-flex" id="venueform">
      <%= link_to root_path do %>
        <i class="fa-solid fa-arrow-left" id="arrow_left"></i>
      <% end %>
      <h3>Create Venue</h3>
    </div>
    <div class="col-md-12" id="createvenue">
      <%= render 'form' %>
    </div>
  </div>
  <div class="row">
    <%= render 'shared/footer'%>
  </div>
</div>

app/views/venues/show.html.erb
<div class="container">
  <div class="row" id="venueshowtop"  style="background-image: url(<%= @venue.photo_url %>); height:61vw; background-size:cover;">
    <%= link_to  front_page_path do %>
      <i class="fa-solid fa-circle-arrow-left" id="arrow_left"></i>
    <% end %>
    <%# add to favorite icon here %>
  </div>
  <div class="row" id="venueshowcard">
    <div class="col-sm-12" id="venuecarddetail">
      <div class="col-sm-12 d-flex mb-3 " style="justify-content: space-between;">
        <h3 style="font-size: 6vw;"><%= @venue.name %></h3>
        <p style="font-size: 4vw;"><i class="fa-solid fa-star" style="color: #deb1fb;"></i><%= @venue.rating %></p>
      </div>
      <div class="venueshowinfo">
        <p style="font-size: 4vw;"><i class="fa-regular fa-envelope"></i><%= @venue.email_address%></p>
        <div class="col-md-12" style="justify-content: space-between;">
          <p style="font-size: 4vw
;"><i class="fa-solid fa-computer-mouse"></i><%= @venue.website%></p>
          <p class="phone" style="font-size: 4vw
;"><i class="fa-solid fa-phone" ></i><%= @venue.phone_number%></p>
          <p style="font-size: 4vw;"><i class="fa-solid fa-location-dot"></i> <%= @venue.address%></p>
          <p style="font-size: 4vw;"><i class="fa-regular fa-clock"></i> <%= @venue.operation_hour%></p>
        </div>
      </div>
    </div>
  </div>
  <div class="row">

    <div class="col-sm-12 mt-2" id="venuedetails">
      <p style="margin-bottom:5vw;"><%= @venue.description %></p>

      <h6 style="font-size: 5vw; margin-bottom:1px;"><em><strong>Type -</strong></em></h6>
      <p><%= @venue.category%></p>
      <h6 style="font-size: 5vw; margin-bottom:1px;"><em><strong>$$ -</strong></em></h6>
      <p style="margin-bottom: 0px;">Estimated price per person</p>
      <p>$<%= @venue.price%></p>
    </div>

    <div class="col-sm-12" id="capacity">

      <h6 style="font-size: 5vw; margin-bottom:1px;"><em><strong>Capacity -</strong></em></h6>
      <p><%= @venue.capacity%> people</p>
    </div>
    <div class="reviewbox mb-3" >
      <h6 style="font-size: 5vw; margin-bottom:1px;"><em><strong>What they say about us:</strong></em></h6>

      <p class='review' style="font-size: 4vw;">"<em><%= @venue.review %><em>"</p>
    </div>
  </div>

  <div class="row">
    <%= render 'bookingform' %>
  </div>
</div>